"""add WhatsApp opt-in columns to player

Hand-written on purpose: the production `player` table differs from the model
(extra legacy columns such as phone_number), so an autogenerated diff would
try to drop/alter unrelated columns. This revision only adds three columns.

Revision ID: a1f3c9d2e7b4
Revises:
Create Date: 2026-09-24

"""
from alembic import op
import sqlalchemy as sa


revision = 'a1f3c9d2e7b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('player', sa.Column('whatsapp_optin', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
    op.add_column('player', sa.Column('whatsapp_optin_at', sa.DateTime(), nullable=True))
    op.add_column('player', sa.Column('optin_requested_at', sa.DateTime(), nullable=True))


def downgrade():
    with op.batch_alter_table('player') as batch_op:
        batch_op.drop_column('optin_requested_at')
        batch_op.drop_column('whatsapp_optin_at')
        batch_op.drop_column('whatsapp_optin')
